services:
  asterisk:
    image: mlan/asterisk
    cap_add:
      - net_admin
      - net_raw
    network_mode: host
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}
      - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
      - PULSE_SERVER=unix:/run/pulse/socket
      - PULSE_COOKIE=/run/pulse/cookie
      - WEBSMSD_PORT=${WEBSMSD_PORT-80}
    volumes:
      - ./config:/etc/asterisk
      - tele-conf:/srv
      - /etc/localtime:/etc/localtime:ro
    restart: always

volumes:
  tele-conf:
